name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          push-to-fork: ci-forks/LocalAI
          commit-message: ":arrow_up: Update ggerganov/whisper.cpp"
          title: ":arrow_up: Update ggerganov/whisper.cpp"
          branch: update/WHISPER_CPP_VERSION
          body: "Bump of ggerganov/whisper.cpp version"
          signoff: true
          committer: GitHub <noreply@github.com>
          author: jaskaran-5ingh <jaskaran-5ingh@users.noreply.github.com>
          delete-branch: false
          draft: false
